### ISSUE TITLE
这个项目不应该是Template

### ISSUE THREAD

**Issue by BaiMeow** [Logiase/MiraiGo-Template#1]
该成为template的应该是Module的template吧?而不是整个项目

**Comment by Logiase** [comment]
其实就一个名字，一开始是打算可以让别人fork整个项目，然后在这个基础上继续开发自己的内容，但写着写着就写到现在的样子了...

**Comment by BaiMeow** [comment]
我个人建议是先取消这个项目的template属性
然后autoreply可以作为示例module,单独开一个MiraiGo-Module-Template给他
开发就开发module

**Comment by Logiase** [comment]
搬好了

**Comment by BaiMeow** [comment]
我觉得能有类似于这个东西的一个template会比较方便开项目
https://github.com/Tnze/CoolQ-Golang-Plugin

**Comment by Logiase** [comment]
这个没太大必要了，本身没有像coolq一样打包dll的需求
