### ISSUE TITLE
当前版本过低，请升级到QQ最新版本。

### ISSUE THREAD

**Issue by sheng-di** [Logiase/MiraiGo-Template#10]
使用 device_test.go 生成 device.json后，登录提示这个。
```bash
time="2021-02-12T11:15:44+08:00" level=info msg="initializing modules ..." bot=internal
time="2021-02-12T11:15:44+08:00" level=info msg="all modules initialized" bot=internal
time="2021-02-12T11:15:44+08:00" level=info msg="registering modules serve functions ..." bot=internal
time="2021-02-12T11:15:44+08:00" level=info msg="all modules serve functions registered" bot=internal
time="2021-02-12T11:15:44+08:00" level=info msg="starting modules tasks ..." bot=internal
time="2021-02-12T11:15:44+08:00" level=info msg="tasks running" bot=internal
time="2021-02-12T11:15:44+08:00" level=fatal msg="login failed: 当前版本过低，请升级到QQ最新版本。" bot=internal
```

**Comment by Mmx233** [comment]
更新依赖中的MiraiGo应该就可以了，

**Comment by Mmx233** [comment]
刚看到这个仓库，纯属路过，未实测上述方法可用性

**Comment by SuzukiHonoka** [comment]
同样情况。
```
time="2021-02-13T22:35:37+08:00" level=info msg="initializing modules ..." bot=internal
time="2021-02-13T22:35:37+08:00" level=info msg="all modules initialized" bot=internal
time="2021-02-13T22:35:37+08:00" level=info msg="registering modules serve functions ..." bot=internal
time="2021-02-13T22:35:37+08:00" level=info msg="all modules serve functions registered" bot=internal
time="2021-02-13T22:35:37+08:00" level=info msg="starting modules tasks ..." bot=internal
time="2021-02-13T22:35:37+08:00" level=info msg="tasks running" bot=internal
time="2021-02-13T22:35:37+08:00" level=fatal msg="login failed: 当前版本过低，请升级到QQ最新版本。" bot=internal
```

**Comment by sheng-di** [comment]
> 同样情况。
> 
> ```
> time="2021-02-13T22:35:37+08:00" level=info msg="initializing modules ..." bot=internal
> time="2021-02-13T22:35:37+08:00" level=info msg="all modules initialized" bot=internal
> time="2021-02-13T22:35:37+08:00" level=info msg="registering modules serve functions ..." bot=internal
> time="2021-02-13T22:35:37+08:00" level=info msg="all modules serve functions registered" bot=internal
> time="2021-02-13T22:35:37+08:00" level=info msg="starting modules tasks ..." bot=internal
> time="2021-02-13T22:35:37+08:00" level=info msg="tasks running" bot=internal
> time="2021-02-13T22:35:37+08:00" level=fatal msg="login failed: 当前版本过低，请升级到QQ最新版本。" bot=internal
> ```

后来就放弃这个项目了，可以直接使用 [http 的那个](https://github.com/Mrs4s/go-cqhttp)，然后自己的语言去请求，也更稳定一些。

**Comment by Logiase** [comment]
更新了依赖, 已经修复
