### ISSUE TITLE
希望能取消历史消息的接收

### ISSUE THREAD

**Issue by kumiko-desu** [Logiase/MiraiGo-Template#12]
机器人启动并接收到一条消息后，miraiGO将会刷新出大量的历史消息，似乎最大消息数量为70条左右，而这可能会导致module中的命令在短时间内被频繁的触发。
比如在加载第三方Module：[logiase.autoreply](https://github.com/Logiase/MiraiGo-module-autoreply)时，根据关键词，机器人可能会在短时间内大量的自动回复，造成疯狂刷屏的情况。

**Comment by kumiko-desu** [comment]
补充：我发现只会在私聊消息中出现这种情况。

**Comment by Logiase** [comment]
了解了

**Comment by Sora233** [comment]
这是miraigo（或者tx）的问题，已经接受过的消息会再次收到

**Comment by Sora233** [comment]
暂时workaround，用msg的Time计算一下
```golang
	bot.OnPrivateMessage(func(qqClient *client.QQClient, msg *message.PrivateMessage) {
		if msg.Time < int32(time.Now().Add(time.Minute*-5).Unix()) {
			return
		}
        }
```

**Comment by kumiko-desu** [comment]
@Sora233 感谢回复，目前我用不到私聊，暂时只用群聊测试了。

**Comment by Sora233** [comment]
最新版miraigo已经修复了这个问题：https://github.com/Mrs4s/MiraiGo/issues/131
