### ISSUE TITLE
当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。

### ISSUE THREAD

**Issue by kris-yi** [Logiase/MiraiGo-Template#14]
time="2021-03-19T17:41:18+08:00" level=fatal msg="login failed: 当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。" bot=internal
请问这个问题该怎么解决？

**Comment by Logiase** [comment]
可能是设备锁？

**Comment by kris-yi** [comment]
> 可能是设备锁？

我的新号没有设备锁，但是注册了有好几个月了，在本地的设备也登陆过
