### ISSUE TITLE
是否考虑直接取消掉生成设备文件这一步，直接在程序启动的时候根据条件生成？

### ISSUE THREAD

**Issue by asjdf** [Logiase/MiraiGo-Template#24]
直接判断所需的device.json是否存在，如不存在直接生成，存在则读取设备文件。
感觉这样更方便，不这么做是有什么顾虑吗？

**Comment by Logiase** [comment]
因为现在的device.json有些些问题，还需要一些特殊方法去生成或者验证

#15
