### ISSUE TITLE
 error="open ./device.json: no such file or directory"

### ISSUE THREAD

**Issue by loshanvren** [Logiase/MiraiGo-Template#3]
`device.json` 文件要怎么获取？

**Comment by Logiase** [comment]
可以新建文件device_test.go

``` go
package main

import (
	"github.com/Logiase/MiraiGo-Template/bot"
	"testing"
)

func Test_GenDeviceJson(t *testing.T) {
	bot.GenRandomDevice()
}
```

运行此test会在当前目录下生成一个device.json

**Comment by loshanvren** [comment]
> 可以新建文件device_test.go
> 
> ```go
> package main
> 
> import (
> 	"github.com/Logiase/MiraiGo-Template/bot"
> 	"testing"
> )
> 
> func Test_GenDeviceJson(t *testing.T) {
> 	bot.GenRandomDevice()
> }
> ```
> 
> 运行此test会在当前目录下生成一个device.json

ok, thx！dalao
