### ISSUE TITLE
bot无法登录

### ISSUE THREAD

**Issue by kumiko-desu** [Logiase/MiraiGo-Template#36]
git clone仓库最新代码，启动bot时，报如下错误。尝试多个账号均报此错误
![image](https://user-images.githubusercontent.com/53305285/146503879-05f7f886-d441-4914-934c-bb27e6577520.png)

**Comment by kumiko-desu** [comment]
测试多台机器，多个网络环境，多个账号均出现此问题。

**Comment by Logiase** [comment]
先尝试更新一下 MiraiGo 依赖

**Comment by kumiko-desu** [comment]
更新依赖后问题解决了，最新的依赖居然要求go版本1.17。
